### PR TITLE
Update Dockerfile & README.md... again.

### PR DESCRIPTION
**Pull request by Peppernrino**
Dockerfile:
* Made python versions more specific and included python2, as some plugins still require it.
* Updated Limnoria version.

README.md:
* Updated backup guide URL.

### CODE REVIEW

**Comment by Peppernrino** [comment]
hopefully i did the python things correctly. :) i need some python2 plugins on my bot.

**Comment by dangmai** [comment]
Thank you for the PR, I really appreciate it. Unfortunately after thinking about it for a bit I don't think we should move Python version back to 2, because it might break other installations that are already using this image. I'll merge the rest of the PR. Please feel free to maintain your fork if you a Python2 version of Limnoria.

**Comment by Peppernrino** [comment]
i thought the python library i used would let it use 2.7 and 3.6 simultaneously... as i want to use python2 and python3 plugins on the same bot (maybe i misunderstand how docker works?) if you think it would break other bots though, it's probably best for me to maintain my own repo as you say. :+1:

**Comment by dangmai** [comment]
I doubt that it works that way - limnoria is invoked by either Python2 or Python3 executable, and the plugin is invoked by limnoria - so the plugins can either run under Python2 or Python3, but not both. Obviously you should play around with it, it's been a while since I developed a plugin for limnoria :)

Good luck!

**Comment by Peppernrino** [comment]
hm. they can't be run side by side? like, a python2 plugin and a python3 plugin on the same bot? i thought the docker container kind of worked as an env for the libraries once loaded.

i'm not meaning to run the same plugin on both pythons at the same time... just clearing up some possible confusion.

**Comment by Peppernrino** [comment]
oh, i get it now. it's because you start python3, and that runs the bot. i thought it was kind of more like instructions that each plugin pulled from... but it's more like a framework that it's running on. still pretty new to development. thank you for your patience. lol :D 

it's weird though, because you don't use, say, `python run.py` for the bot... it's in a .conf file. i'm going to do some tests of my own and get back to you on this.

**Pull request merged**
